name:                recursion-schemes-ix
version:             0.1.0.0
github:              "Skyb0rg007/recursion-schemes-ix"
license:             BSD3
author:              "Skye Soss"
maintainer:          "skyler.soss@gmail.com"
copyright:           "2020 Skye Soss"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Recursion schemes over indexed Functors
category:            Data

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Skyb0rg007/recursion-schemes-ix#readme>

tested-with: GHC == 8.6.5
           , GHC == 8.8.3
           , GHC == 8.10.1
           , GHCJS == 8.6.0.1

dependencies:
- base >= 4.12 && < 4.15
- singlethongs == 0.1

library:
  source-dirs: src

tests:
  recursion-schemes-ix-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - recursion-schemes-ix
    - hspec
    - mtl
    - QuickCheck
    - containers
